# Generated by Django 5.1.1 on 2024-11-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='people_count',
        ),
    ]
