# Generated by Django 5.1.1 on 2024-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0012_rename_quantity_product_people_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
