# Generated by Django 5.1.1 on 2024-11-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0013_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='people_now_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
