# Generated by Django 5.1.1 on 2024-11-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0014_product_people_now_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('product_name', models.CharField(max_length=100)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('receivable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_number', models.CharField(max_length=100)),
                ('courier_service', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_products', to='mypage.product')),
                ('registrant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
