# Generated by Django 5.1.1 on 2024-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0015_registeredproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredproduct',
            old_name='photo_url',
            new_name='product_image_url',
        ),
        migrations.AddField(
            model_name='registeredproduct',
            name='product_link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
