# Generated by Django 5.1.1 on 2024-11-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0016_rename_photo_url_registeredproduct_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredproduct',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='registeredproduct',
            name='product_link',
        ),
        migrations.RemoveField(
            model_name='registeredproduct',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='registeredproduct',
            name='purchase_amount',
        ),
        migrations.RemoveField(
            model_name='registeredproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='registeredproduct',
            name='receivable_amount',
        ),
        migrations.AlterField(
            model_name='registeredproduct',
            name='courier_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredproduct',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
