# Generated by Django 5.1.1 on 2024-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0017_remove_registeredproduct_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredproduct',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredproduct',
            name='receivable_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
