# Generated by Django 5.1.1 on 2024-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0018_registeredproduct_purchase_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredproduct',
            name='courier_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registeredproduct',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
