# Generated by Django 5.1.1 on 2024-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0021_rename_user_participant_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
