# Generated by Django 5.1.1 on 2024-11-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0022_participant_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mypage.registeredproduct'),
            preserve_default=False,
        ),
    ]
