# Generated by Django 5.1.1 on 2024-11-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0023_participant_registered_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
