# Generated by Django 5.1.1 on 2024-11-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0024_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
