# Generated by Django 5.1.1 on 2024-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0025_remove_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
